server:
  port: 8082
spring:
  rabbitmq:
    port: 5672
    username: admin
    password: 123456
    virtual-host: my_vhost
    host: 192.168.80.131
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 路由失败回调
    publisher-returns: true
    listener:
      simple:
        # 签收模式为手动签收-那么需要在代码中手动ACK
        acknowledge-mode: manual
        # 每次从RabbitMQ获取的消息数量
        prefetch: 1
        default-requeue-rejected: false
        # 每个队列启动的消费者数量
        concurrency: 1
        # 每个队列最大的消费者数量
        max-concurrency: 1
    template:
      # 必须设置成true 消息路由失败通知监听者，false 将消息丢弃
      mandatory: true