spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.kapcb.ccc.mapper: debug

# 查看自动配置信息
# debug: true
